export const MASTER_SKILLS: string[] = [
  "Leadership","Stakeholder Management","Product Strategy","Financial Modeling","SQL","Python",
  "Data Analysis","Project Management","Cross-functional Collaboration","Pricing Strategy",
  "Go-to-Market","Machine Learning","Tableau","Forecasting","A/B Testing","P&L Management",
  "Venture Capital","Private Equity","Due Diligence","Valuation","DCF","LBO","M&A",
  "Consulting","Business Development","Negotiation","Market Research","Competitive Analysis",
  "Product Management","Design Thinking","Supply Chain","Marketing","Brand Management",
  "Growth","Sales","Fundraising","ESG","Sustainability","Risk Management","Compliance",
  "Fintech","SaaS","B2B","B2C","AWS","Figma","Salesforce","Jira","GitHub",
  "Strategic Planning","Executive Communication","Change Management","Team Building",
  "Organizational Design","Recruiting","Performance Management","Budgeting","Cost Reduction",
  "Revenue Growth","Customer Success","Customer Experience","UX Research","Data Visualization",
  "Business Intelligence","Excel","PowerPoint","R","Stata","SPSS","NLP","Deep Learning",
  "Computer Vision","Statistics","Probability","Regression Analysis","Econometrics",
  "Healthcare","Biotech","Pharmaceuticals","Real Estate","Asset Management","Portfolio Management",
  "Fixed Income","Equity Research","Credit Analysis","Derivatives","Trading","Investment Banking",
  "Corporate Finance","Treasury","Accounting","GAAP","IFRS","Audit","Tax","FP&A",
  "Operations","Lean","Six Sigma","Process Improvement","Quality Assurance","Logistics",
  "Procurement","Vendor Management","Contract Negotiation","Legal","Regulatory Affairs",
  "Public Policy","Government Relations","Communications","Public Relations","Content Strategy",
  "SEO","Digital Marketing","Paid Acquisition","Social Media","Email Marketing","CRM",
  "Partnerships","Channel Management","E-commerce","Retail","Consumer Goods","Hospitality",
  "EdTech","Climate Tech","AgriTech","Cybersecurity","Cloud Computing","DevOps","Agile","Scrum",
  "Product Analytics","Cohort Analysis","LTV/CAC","Unit Economics","Market Sizing","Case Interview",
  "Presentation Skills","Written Communication","Facilitation","Coaching","Mentoring",
  "Cultural Competency","Global Markets","Emerging Markets","Latin America","APAC","EMEA",
  "Mandarin","Spanish","French","Arabic","Japanese","Portuguese",
  "API Integration","NoSQL","Snowflake","dbt","Spark","Kafka","Terraform","Docker","Kubernetes",
];
